home:
    pattern: /
    defaults: { _controller: RCloudUserBundle:Dashboard:show }

r_cloud_r:
    resource: "@RCloudRBundle/Controller/"
    type:     annotation
    prefix:   /

r_cloud_user:
    resource: "@RCloudUserBundle/Controller/"
    type: annotation
    prefix: /user

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /user/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /user/profile